# プレフィックスを Ctrl+Aに変更
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# 画面分割をわかりやすいキーに
bind \ split-window -h
bind - split-window -v

# マウス操作を有効化
set -g mouse on

# 色を256色に
set -g default-terminal "screen-256color"
